#!/bin/bash
source ~/.config/goblocks/colors

var=`~/.config/goblocks/goblocks-contrib/volume-pulseaudio/volume-pulseaudio2`
string="${var//  /}"
#printf '%s\n' "${string%"${string#?}"} ${string#?}"
#echo $var2

echo "<span color='$volumeTextColor' font_desc='$fontDesc'> $string</span>"
