#!/usr/bin/env bash
source ~/.config/goblocks/colors

DATE=$(date '+%a %b %d')

echo "<span color='$dateIconColor'> $dateIcon </span><span color='$dateTextColor' font_desc='$fontDesc'>$DATE </span>"

