#!/usr/bin/env bash
source ~/.config/goblocks/colors

var=`~/.config/goblocks/goblocks-contrib/memory/memory2`

echo "<span color='$memoryIconColor'> $memoryIcon</span><span color='$memoryTextColor' font_desc='$fontDesc'> $(echo $var | cut -d " " -f1) </span>"
